modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="${mod_issuesurl}"
license="Public Domain"

[[mods]]
    modId="${mod_id}"
    displayName="${mod_name}"
    description="${mod_description}"
    version="${mod_version}"
    displayURL="${mod_url}"
    authors="${mod_author}"
    updateJSONURL="${mod_updateurl}"

[[dependencies.letmesleep]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.letmesleep]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"